### ISSUE TITLE
Full support of Russian plural forms

### ISSUE THREAD

**Issue by f0ma** [maxyc/flarum-i18n-russian#1]
Нужна ли полная поддержка всех трех форм множественного числа?

Я нашел только одно употребление

```
  unread_posts:
    one: "{count} непрочитанное сообщение"
    two: "{count} непрочитанных сообщения"
    other: "{count} непрочитанных сообщений"
```
Тем не менее потребуется делать три версии для всех плюральных строк. Я готов сделать fork and pull request, если будет решено сделать полную поддержку сабжа.
